project_name         = "acme-poc"
environment          = "sandbox"
name_prefix          = "acme"
fw_ami_id            = "ami-033e1082ab3e1026a"
fw_key_name          = "acme-admin-key"
bootstrap_s3_bucket  = "acme-pan-bootstrap-usw2"
log_s3_bucket_name   = "acme-sandbox-logs-usw2-poc"
admin_cidr           = "75.155.9.209/32"
